### ISSUE TITLE
[Functionality] Approval Referendum

### ISSUE THREAD

**Issue by bill-pap** [galaniprojects/Polkadot-Bounty-Manager#108]
[UI](https://b-t-e.invisionapp.com/console/Bounty-Manager-clwqlb4za00oz017seqszhz01/clzsmzcwb09do016j7buf3gna/play)

- [ ] The user can land on this tab either by proceeding from the previous step, or from the home page view of the bounty. **Functionality not in this issue** _See #126_
- [ ] Clicking on the title bar returns the user to the home page **Functionality not in this issue**
- [ ] The bounty title is prefilled.
- [ ] The treasury track is preselected based on the bounty value. galaniprojects/Polkadot-Bounty-Manager#78 
- [ ] The user can still select a different track from the dropdown.
- [ ] Small spender up to 10000 DOT.
- [ ] Medium spender up to 100000 DOT.
- [ ] Big Spender up to 1000000 DOT. 
- [ ] The transaction fees change depending on the information.
- [ ]  The cancel button returns the user to the main screen. **Functionality not in this issue** _See #127_
- [ ]  The submit button starts the process of signing the transaction.
- [ ] Successful creation shows the newly created refrendum ID in the success page.
- [ ] Extrinsic for referendum [bounties, approveBounty].

Diagram galaniprojects/Bounty-Manager-Issues#61
