### ISSUE TITLE
[Functionality] Curator Proposal

### ISSUE THREAD

**Issue by bill-pap** [galaniprojects/Polkadot-Bounty-Manager#109]
[UI](https://b-t-e.invisionapp.com/console/Bounty-Manager-clwqlb4za00oz017seqszhz01/clzto9nsp0bb5016j88904km9/play)

- [ ] The user can land on this tab either by proceeding from the previous step, or from the home page view of the bounty. **Home page redirection not in this issue.** _See #126_
- [ ] Clicking on the title bar returns the user to the home page **Functionality not in this issue**
- [ ] The bounty title is prefilled.
- [ ] The treasury track is preselected based on the bounty value.
- [ ] The user can still select a different track from the dropdown.
- [ ] The transaction fees change depending on the information.
- [ ] The cancel button returns the user to the main screen. **Functionality not in this issue** _See #127_
- [ ] The submit button starts the process of signing the transaction.
- [ ] Successful creation shows the newly created refrendum ID in the success page.
- [ ] This referendum can only be executed AFTER the bounty is funded, meaning the Approval Referendum galaniprojects/Polkadot-Bounty-Manager#108, has to be pass (after ~28 days) and the spending period is completed (up to 24 days after execution of the referendum). If the Curator Proposal referendum is approved and attempts to execute before the Bounty Approval is executed it will fail.
- [ ] Extrinsic for referendum [bounties, proposeCurator]

Diagram galaniprojects/Bounty-Manager-Issues#62
