### ISSUE TITLE
[Functionality] Estimated Fees and Bonds

### ISSUE THREAD

**Issue by bill-pap** [galaniprojects/Polkadot-Bounty-Manager#123]
In any transaction with the blockchain the estimated transaction fee (and where applicable, deposit or bond) is displayed before the user submits it.
The value should deviate by only a small margin from the real price. Initial target <1%.

Instances include:

- [ ] Creating a bounty #105.
- [ ] Creating a referendum #108 and #109.

All curator actions. This will be expanded later with the correct Issue numbers. Currently:
- [ ] Add child bounty #81.
- [ ] Assign sub-curator #75.
- [ ] Unassign sub-curator #84.
- [ ] Close child bounty #85.
- [ ] Award child bounty #87.
- [ ] Accept curator role #65.
- [ ] Beneficiary claim form #60.

UI sample. 
_Note that the UI will be updated to display Estimated Bounty Bond and Estimated Transaction Fee_

![Image](https://github.com/user-attachments/assets/f140f698-af1e-4fa1-b49e-180f0d15fc46)
