### ISSUE TITLE
[UI] Child Bounty Card

### ISSUE THREAD

**Issue by WaleedKTareen** [galaniprojects/Polkadot-Bounty-Manager#135]
- [ ] Colour coded title bar. Explained in #131 
- [ ] Name and Number of Child Bounty
- [ ] Created on
- [ ] Status of the child bounty. Explained in #68.
- [ ] Value of child bounty.
- [ ] Sub-curator. If created shows “-”. Otherwise shows address of sub curator.
- [ ] Hovering over the subcurator brings a modal with info and links to the address, as well as the unassign button when applicable.
- [ ] Sub Curator fee.
- [ ] Description. Same as parent bounty.
- [ ] External links. Same as parent bounty.
- [ ] Beneficiary address. Where applicable.
- [ ] Action Buttons (Explained in Issues #75, #84, #85, #134)
- [ ] Collapsed view will have bounty number and name, created on and statuts of the child bounty.
- [ ] Expanded view will have the rest of the information.

Functionality: #140 

[Link to Invision](https://b-t-e.invisionapp.com/console/Bounty-Manager-clwqlb4za00oz017seqszhz01/cm1qkszc701ub01a4graa1bpr/play
