### ISSUE TITLE
[Functionality] Child Bounty Card

### ISSUE THREAD

**Issue by WaleedKTareen** [galaniprojects/Polkadot-Bounty-Manager#140]
- [ ] Title bar colour will change depending on the status of the title bar. Explained in #131 
- [ ] Value will be the total value of the child bounty in dots.
- [ ] Fees for the sub-curator should be shown accordingly.
- [ ] The description same as parent bounty.
- [ ] Hovering over the subcurator brings a modal with info and links to the address, as well as the unassign button when applicable.
- [ ] Action Buttons (Explained in Issues #75 , #84 , #85 , #134)
- [ ] The main title section of the child bounty will have the child bounty name and number and status (for example added, payout pending, awarded). The status of the child bounties is explained in #68 
- [ ] If a sub-curator has not been proposed for the child bounty there would be an assign button. This button would only appear if there is no sub-curator for the child bounty. (Functionality for the button assign is explained in #74 and #75)

Note: The payout delay will become deprecated, so the time until claimable will disappear.
Note: In the UX there is an "AWARD" button in the expanded view of the child bounty this is not going to be shown to the main curator. This button will only be shown to the sub-curator to whom the bounty has been assigned to (explained in a different user story).

UI: #135 

[Link to Invision](https://b-t-e.invisionapp.com/console/Bounty-Manager-clwqlb4za00oz017seqszhz01/cm0usioqo0f4y01cofz044n7e/play)
