### ISSUE TITLE
[UI] Bounty Approval Referendum Success Screen

### ISSUE THREAD

**Issue by bill-pap** [galaniprojects/Polkadot-Bounty-Manager#38]
Dependent on galaniprojects/Polkadot-Bounty-Manager#6 and galaniprojects/Polkadot-Bounty-Manager#37
If the process is successful, the user sees the screen update with a success message with the new referendum ID and a link to the Referendum on Polkassembly (or other platforms), as well as the prompt to update the description there and place the decision deposit within 7 days.

- [x] galaniprojects/Polkadot-Bounty-Manager#43
- [x] galaniprojects/Polkadot-Bounty-Manager#39
- [ ] galaniprojects/Bounty-Manager-Issues#38
- [x] galaniprojects/Bounty-Manager-Issues#37
- [x] galaniprojects/Polkadot-Bounty-Manager#42
- [x] galaniprojects/Polkadot-Bounty-Manager#46

![image](https://github.com/user-attachments/assets/c30d2ae8-2e89-4510-ac27-0c48ae6c0c3a)
